### ISSUE TITLE
/ does not have correct behavior relative to Windows file: URLs

### ISSUE THREAD

**Issue by domenic** [annevk/url#1]
``` js
var base = new jURL("file:///C:/Users/Domenic/Dropbox/Programming/GitHub/jsdom/test/jsdom/index.js");

var resolved = new jURL("/", base);

console.log(resolved.href);
```

Gives `"file:///"`, but should give `"file:///C:/"`.

**Comment by annevk** [comment]
Is that what Internet Explorer does? I think I tested this...

**Comment by annevk** [comment]
Hmm, it does. Chrome does too. Firefox doesn't.

**Comment by annevk** [comment]
This repository is no longer maintained, but this should behave correctly in the specification now.
