### ISSUE TITLE
relative urls fail to resolve if 'base' argument is not a jURL object

### ISSUE THREAD

**Issue by dfreedm** [annevk/url#5]
## Expected

``` js
new jURL('foo', 'http://example.com').href === 'http://example.com/foo'
```
## Actual

``` js
new jURL('foo', 'http://example.com').href === 'foo'
```
## Inplace Fix

I put this before the `defineProperties` block, which seems to work (ignoring encoding).

``` js
if (typeof base === 'string') {
  base = new jURL(base)
}
```

**Comment by annevk** [comment]
Closing since I'm not actively maintaining this. My apologies for the extremely late reply.
