### ISSUE TITLE
type of base on constructor

### ISSUE THREAD

**Issue by Jxck** [annevk/url#6]
in spec says type of base is USVString

https://url.spec.whatwg.org/#api

```
[Constructor(USVString url, optional USVString base = "about:blank"), Exposed=(Window,Worker)]
interface URL {
  static USVString domainToASCII(USVString domain);
  static USVString domainToUnicode(USVString domain);
};
```

but in this test runner
https://github.com/annevk/url/blob/master/urltestrunner.html#L31

``` js
url = new jURL(test.input, new jURL(test.base))
```

base is jURL instance.

which is correct?

**Comment by annevk** [comment]
The specification. I recommend using the tests from https://github.com/w3c/web-platform-tests instead.

**Comment by Jxck** [comment]
thanks
